# Generated by Django 3.2.19 on 2023-10-29 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MengelolaBuku', '0005_pengguna_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Komunitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('point', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MengelolaBuku.buku')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Komunitas.community')),
                ('reply', models.ManyToManyField(blank=True, to='ChallengeLeaderboard.Reply')),
            ],
        ),
    ]
