# Generated by Django 3.2.19 on 2023-10-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Komunitas', '0001_initial'),
        ('ChallengeLeaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Komunitas.community'),
        ),
    ]
