# Generated by Django 3.2.19 on 2023-10-28 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MengelolaBuku', '0004_buku_image_url'),
        ('Komunitas', '0001_initial'),
        ('ChallengeLeaderboard', '0002_challenge_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MengelolaBuku.buku'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Komunitas.community'),
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='reply',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='reply',
            field=models.ManyToManyField(to='ChallengeLeaderboard.Reply'),
        ),
    ]
