# Generated by Django 3.2.19 on 2023-10-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeLeaderboard', '0003_alter_challenge_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='reply',
            field=models.ManyToManyField(blank=True, to='ChallengeLeaderboard.NewReply'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
