# Generated by Django 3.2.19 on 2023-10-29 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChallengeLeaderboard', '0003_auto_20231028_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('point', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='books',
            new_name='book',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='reply',
            field=models.ManyToManyField(blank=True, to='ChallengeLeaderboard.NewReply'),
        ),
    ]
