# Generated by Django 3.2.19 on 2023-10-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeLeaderboard', '0003_auto_20231028_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='books',
            new_name='book',
        ),
    ]
