# Generated by Django 3.2.19 on 2023-10-28 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChallengeLeaderboard', '0004_rename_books_challenge_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='id',
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
