# Generated by Django 3.2.19 on 2023-10-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChallengeLeaderboard', '0005_auto_20231029_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
