# Generated by Django 3.2.19 on 2023-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeLeaderboard', '0006_auto_20231029_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
