# Generated by Django 3.2.19 on 2023-10-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeLeaderboard', '0007_reply_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='reply',
            field=models.ManyToManyField(blank=True, default=set, to='ChallengeLeaderboard.Reply'),
        ),
    ]
