# Generated by Django 3.2.19 on 2023-12-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0010_auto_20231209_1256'),
        ('ChallengeLeaderboard', '0007_alter_reviews_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('is_guru', models.BooleanField()),
                ('banyak_review', models.IntegerField(default=0)),
                ('banyak_bintang', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MengelolaBuku.pengguna')),
            ],
        ),
    ]
