# Generated by Django 3.2.19 on 2023-12-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeLeaderboard', '0008_leaderboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
