# Generated by Django 3.2.19 on 2023-10-25 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MengelolaBuku', '0002_buku_num_of_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guru',
            new_name='Pengguna',
        ),
    ]
