# Generated by Django 3.2.19 on 2023-10-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0003_rename_guru_pengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='image_url',
            field=models.TextField(default='XXX'),
            preserve_default=False,
        ),
    ]
