# Generated by Django 4.2.5 on 2023-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0006_alter_pengguna_isguru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='isGuru',
            field=models.BooleanField(),
        ),
    ]
