# Generated by Django 3.2.19 on 2023-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0007_alter_pengguna_isguru'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='banyak_bintang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='banyak_review',
            field=models.IntegerField(default=0),
        ),
    ]
