# Generated by Django 4.2.5 on 2023-12-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0007_alter_pengguna_isguru'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='banyakBintang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='banyakReview',
            field=models.IntegerField(default=0),
        ),
    ]
