# Generated by Django 3.2.19 on 2023-12-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0008_auto_20231206_1349'),
        ('MengelolaBuku', '0008_pengguna_banyakbintang_pengguna_banyakreview'),
    ]

    operations = [
    ]
