# Generated by Django 3.2.19 on 2023-12-20 06:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0011_alter_buku_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=500),
        ),
    ]
