# Generated by Django 3.2.19 on 2023-12-20 06:26

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books_new.json")

class Migration(migrations.Migration):

    dependencies = [
        ('MengelolaBuku', '0012_auto_20231220_1326'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]