# Generated by Django 4.2.6 on 2023-10-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komunitas', '0002_discussion_remove_community_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='email',
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(default='anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
