# Generated by Django 4.2.6 on 2023-10-28 08:17

from django.conf import settings
from django.db import migrations, models
import komunitas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('komunitas', '0003_remove_community_email_alter_community_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='topic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='community',
            name='link',
        ),
        migrations.AddField(
            model_name='community',
            name='join_code',
            field=models.CharField(default=komunitas.models.generate_join_code, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
