# Generated by Django 3.2.22 on 2023-10-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_teacher',
            new_name='isGuru',
        ),
    ]
