# Generated by Django 4.2.5 on 2023-12-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0002_rename_is_teacher_userprofile_isguru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
